# Basic config
seed: 2023
epochs: 2000
lr: 0.0001
batch_size: 1
num_workers: 4
context: False
context_col: [0] # 0 - 4 or 11
class_lr: 0.001
class_epochs: 1000
class_batch_size: 64

# Train config
clip_grad: True
ema_decay: 0.999
include_an: True
include_de: True
train_subset: False

# Model config
num_layers: 3
node_emb_dim: 129
emb_dim: 128
hidden_dim: 256
num_heads: 8
loss_type: l2
dropout: 0.1
diff_step: 500
noise_schedule: polynomial_2
noise_precision: 0.00001
n_dim: 3 # dimension of data
pair_loss_scale: 0.0
cutoff: 10
calc_dl: True
loss_weight: {
        'degree': 0.01
}
add_time: False
block_calc: True

# Eval config
valid_iter: 20
analyze_threshold: 0
analyze_iter: 20
n_samples: 40
sample_batch_size: 2

enable_tb: True
load_ckpt: Ture
load_ckpt_dir: ckpt/
class_ckpt_dir: ckpt
ckpt_dir: ckpt
log_dir: log
