
seed: 2023
epochs: 1
lr: 0.0001
batch_size: 16
num_workers: 4
context: True
context_col: [0] # 0 - 4 or 11
class_lr: 0.001
class_epochs: 1
class_batch_size: 64

clip_grad: True
ema_decay: 0.999
include_an: True
include_de: True
train_subset: False

num_layers: 3
node_emb_dim: 129
emb_dim: 128
hidden_dim: 256
num_heads: 8
loss_type: l2
dropout: 0.1
diff_step: 500
noise_schedule: polynomial_2
noise_precision: 0.00001
n_dim: 3
pair_loss_scale: 0.0
cutoff: 10
calc_dl: True
loss_weight: {'degree': 0.01}
add_time: False
block_calc: True

valid_iter: 20
analyze_threshold: 1000
analyze_iter: 20
n_samples: 40
sample_batch_size: 2

enable_tb: True
load_ckpt: False
load_ckpt_dir: ckpt/
classifier_ckpt_dir: ckpt/
ckpt_dir: ckpt
log_dir: log
